services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - "./503.html:/usr/share/nginx/html/503.html"
  sso:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_RELATIVE_PATH=/auth
    command: start
    volumes:
      - data:/opt/keycloak/data
      - ./providers/:/opt/keycloak/providers

volumes:
  data:
    name: keycloak_data
    driver: local

networks:
  default:
    name: keycloak_network
